version: '3'
services:
  server:
    build:
      context: .
      dockerfile: "Dockerfile"
      args:
        MYSQL_HOST: ${MYSQL_HOST}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 80:3000
    volumes:
      - .:/myapp:cached
    depends_on:
      - db
    env_file: .env
  db:
    image: mysql:5.7
    volumes:
      - ./db/mysql:/var/lib/mysql:cached
      - ./config/docker/mysql/conf.d:/etc/mysql/conf.d:cached
    env_file: .env
    ports:
      - "3306:3306"
