version: '3'
services:
  server:
    build:
      context: .
      dockerfile: "Dockerfile"
    target: webserver
    command: ['rails', 's']
    ports:
      - 80:3000
    volumes:
      - .:/myapp
    depends_on:
      - db
    env_file: .env
    restart: always
  db:
    image: mysql:5.7
    volumes:
      - ./db/mysql:/var/lib/mysql
    env_file: .env
    ports:
      - "3306:3306"
    restart: always
