source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.5.1"

# Bundle edge Rails instead: gem "rails", github: "rails/rails"
gem "rails", "~> 5.2.0"
# Use sqlite3 as the database for Active Record
gem "mysql2"
gem "sass-rails"
gem "uglifier"
gem "coffee-rails"
gem "therubyracer"
gem "jquery-rails"
gem "turbolinks"
gem "jbuilder"
gem "bcrypt"
gem "nokogiri"
gem "rack-cors"
gem "devise"
gem "byebug"
gem "rspec"
gem "rspec-rails"
gem "rspec-collection_matchers"
gem "better_errors"
gem "factory_girl_rails"
gem "guard-rspec", require: false
gem "faker"
gem "pry"
gem "database_cleaner"
gem "rubocop"
gem "rubocop-checkstyle_formatter"
gem "brakeman", "3.4.1"
gem "jshint"
gem "bundler-audit"
gem "scss_lint"
gem "scss_lint_reporter_checkstyle"
gem "eslint-rails"
gem "rails_best_practices"
gem "web-console"
gem "listen"
gem "spring"
gem "spring-watcher-listen"
gem "simplecov"
gem "simplecov-rcov"
gem "simplecov-json"
gem "shoulda-matchers"
gem "capistrano"
gem "capistrano-bundler"
gem "capistrano-rails"
gem "capistrano-rvm"
gem "capistrano-passenger"
gem "capistrano3-unicorn"
gem "unicorn"
gem "tzinfo-data"
gem "dotenv-rails"
gem "config"
gem "unicorn-worker-killer"
gem "kaminari"
gem "bootstrap-kaminari-views"
gem "sidekiq"
gem "sidekiq-cron"
gem "redis-rack", git: "https://github.com/redis-store/redis-rack.git", branch: "master"
gem "redis-actionpack", git: "https://github.com/redis-store/redis-actionpack.git", branch: "master"
gem "redis-rails", git: "https://github.com/redis-store/redis-rails", branch: "master"
gem "redis-namespace"
gem "sinatra"
gem "figaro"
gem "slim"
gem "cancancan"
gem "paranoia"
gem "ransack"
gem "state_machines-activerecord"
gem "carrierwave"
gem "fog"
gem "aws-sdk", "~> 2"
gem "grape", ">= 1.1.0"
gem "active_model_serializers"
gem "whenever", require: false
gem "rest-client"
gem "hashie"
gem "mini_magick"
gem "puma"
gem "faraday"
gem "parallel"
gem "google-analytics-rails"
gem "oauth2"
gem "paperclip"
gem "elasticsearch"
gem "rails_admin"
gem "activeadmin"
gem "draper"
gem "will_paginate"
gem "sqlite3"
gem "meta-tags"
gem "arel"
gem "ffi"
gem "react-rails"
gem "webmock"
gem "moji"
gem "rswag"
gem "whenever-test"
gem "state_machines-activerecord"
gem "haml-rails"
gem "mimemagic"
gem "acts_as_votable"
gem "aws-sdk"
gem "simple_captcha2"
gem "activerecord-import"
gem "omniauth-facebook"
gem "warden"
gem "pg"