default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV['MYSQL_HOST'] %>
  timeout: 5000

development:
  <<: *default
  database: vcl_development

test:
  <<: *default
  database: vcl_test

production:
  <<: *default
  database: vcl_production
