access_token_header: "Xx-Authorization"

http_code:
  code_200: 200
  code_400: 400
  code_404: 404
  code_401: 401
  code_403: 403

error_formatter:
  message_key: "message"
  http_code:
    data_operation: 422
    unauthorized: 401
    not_authorized_error: 401
    token_expired: 401
    record_not_found: 404
    validation_errors: 400
    wrong_email_password: 400
    wrong_current_password: 400
    unauthenticated: 401
    decode_error: 401
    verification_error: 401

http_code:
  code_200: 200
  code_400: 400
  code_404: 404
  code_401: 401
  code_403: 403

validations:
  strings:
    max_length: 255
  email_regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/'
  password_regex: !ruby/regexp '/^(?=.*\d)(?=.*[#$@!%&*?])[A-Za-z\d#$@!%&*?]{8,}$/'

user_tokens:
  token:
    secure_length: 64
  refresh_token:
    secure_length: 64
  expires_in: <%= 30.days %>
  short_expires_in: <%= 1.days %>
